version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - app_network
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    networks:
      - app_network
  rust_server:
    build:
      context: ./rust_server
      dockerfile: Dockerfile
    container_name: rust_server
    ports:
      - "8080:8080" # External debug connection
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: postgres
    depends_on:
      - redis
      - postgres
    networks:
      - app_network
    restart: always

volumes:
  redis_data:
  pg_data:

networks:
  app_network:
    driver: bridge