//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tb_alarm_model")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub time: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub message: String,
    pub repeat_circle: Option<String>,
    pub repeat_end_at: Option<DateTime>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub user_id: i32,
    pub user_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
