//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tb_context_to_msg_id")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub ai_msg: i64,
    pub ai_context: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::tb_ai_context::Entity")]
    TbAiContext,
}

impl Related<super::tb_ai_context::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TbAiContext.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
