//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tb_debt_receipt")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub debtor_id: i32,
    pub amount: i64,
    pub created_at: DateTimeWithTimeZone,
    pub is_cleared: bool,
    pub cleared_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tb_debtor::Entity",
        from = "Column::DebtorId",
        to = "super::tb_debtor::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TbDebtor,
}

impl Related<super::tb_debtor::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TbDebtor.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
