//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tb_discord_message_to_at_context")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub discord_message: i64,
    pub ai_context_id: i64,
    pub ai_msg_id: i64,
    pub update_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tb_discord_ai_context::Entity",
        from = "Column::AiContextId",
        to = "super::tb_discord_ai_context::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TbDiscordAiContext,
}

impl Related<super::tb_discord_ai_context::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TbDiscordAiContext.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
