//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tb_discord_ai_context")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub guild_id: i64,
    pub root_msg: i64,
    pub using_pro_model: bool,
    pub parent_context: Vec<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tb_discord_message_to_at_context::Entity")]
    TbDiscordMessageToAtContext,
}

impl Related<super::tb_discord_message_to_at_context::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TbDiscordMessageToAtContext.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
