//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tb_image_attach_file")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub image_id: i64,
    #[sea_orm(column_type = "Text")]
    pub file_src: String,
    pub mime_type: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tb_ai_context::Entity")]
    TbAiContext,
}

impl Related<super::tb_ai_context::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TbAiContext.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
